include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    use_build_context_synchronously: ignore
    avoid_print: ignore
    deprecated_member_use: ignore
    unnecessary_null_comparison: ignore
