name: neetiflow
description: "A universal CRM system for managing business tasks and operations"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.6.10
  
  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.3
  equatable: ^2.0.5
  
  # UI Components
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.0.0
  fl_chart: ^0.63.0
  table_calendar: ^3.1.0
  file_picker: ^5.3.3
  csv: ^6.0.0
  universal_html: ^2.2.4
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3
  path: ^1.9.0
  logger: ^2.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  go_router: ^14.6.1
  meta: ^1.12.0
  timeline_tile: ^2.0.0
  timelines: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  bloc_test: ^9.1.6
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic
