name: neetiflow
description: "A universal CRM system for managing business tasks and operations"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # Firebase
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.6.10
  
  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.3
  equatable: ^2.0.5
  
  # UI Components
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  flutter_secure_storage: ^9.0.0
  fl_chart: ^0.63.0
  table_calendar: ^3.1.0
  file_picker: ^5.3.3
  csv: ^6.0.0
  universal_html: ^2.2.4
  timeline_tile: ^2.0.0
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.2.0
  path: ^1.9.0
  logger: ^2.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
  go_router: ^14.6.1
  meta: ^1.12.0

  rxdart: ^0.28.0
  timeago: ^3.7.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  injectable: ^2.5.0
  get_it: ^8.0.2
  flutter_colorpicker: ^1.1.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.4.1
  bloc_test: ^9.1.6
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/optimization.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/optimization.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/optimization.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/optimization.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic
