// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYpIqRcN87PbhlyxJ-A9rlK8aUjJRFbl8',
    appId: '1:691923559988:web:cd2724642769eb9e69cc61',
    messagingSenderId: '691923559988',
    projectId: 'neeti-flow-crm',
    authDomain: 'neeti-flow-crm.firebaseapp.com',
    storageBucket: 'neeti-flow-crm.firebasestorage.app',
    measurementId: 'G-VXQCTEH2SG',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYpIqRcN87PbhlyxJ-A9rlK8aUjJRFbl8',
    appId: '1:691923559988:web:cd2724642769eb9e69cc61',
    messagingSenderId: '691923559988',
    projectId: 'neeti-flow-crm',
    authDomain: 'neeti-flow-crm.firebaseapp.com',
    storageBucket: 'neeti-flow-crm.firebasestorage.app',
    measurementId: 'G-VXQCTEH2SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYpIqRcN87PbhlyxJ-A9rlK8aUjJRFbl8',
    appId: '1:691923559988:android:cd2724642769eb9e69cc61',
    messagingSenderId: '691923559988',
    projectId: 'neeti-flow-crm',
    storageBucket: 'neeti-flow-crm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYpIqRcN87PbhlyxJ-A9rlK8aUjJRFbl8',
    appId: '1:691923559988:ios:cd2724642769eb9e69cc61',
    messagingSenderId: '691923559988',
    projectId: 'neeti-flow-crm',
    storageBucket: 'neeti-flow-crm.firebasestorage.app',
    iosClientId: '691923559988-ios.apps.googleusercontent.com',
    iosBundleId: 'com.neetiflow.crm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYpIqRcN87PbhlyxJ-A9rlK8aUjJRFbl8',
    appId: '1:691923559988:macos:cd2724642769eb9e69cc61',
    messagingSenderId: '691923559988',
    projectId: 'neeti-flow-crm',
    storageBucket: 'neeti-flow-crm.firebasestorage.app',
    iosClientId: '691923559988-macos.apps.googleusercontent.com',
    iosBundleId: 'com.neetiflow.crm.macos',
  );
}
